# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xW8VKgKd0bNdiT9G56I74fXWA1zpx-h3
"""



"""1. Why are functions advantageous to have in your programs?
Ans: makes programs shorter, easier to read, and easier to update
2. When does the code in a function run: when it's specified or when it's called?
Ans: When it is called
3. What statement creates a function?
Ans: def keyword ():
4. What is the difference between a function and a function call?
Ans: A function is a piece of code. A function call means invoking or calling that function. Unless a function is called there is no use of that function.
5. How many global scopes are there in a Python program? How many local scopes?
Ans: A global variable has global scope. A global variable is accessible from anywhere in the code. Local Scope — Local scope contains things defined inside code blocks. A local variable has local scope.
6. What happens to variables in a local scope when the function call returns?
Ans: the local variables are destroyed.
7. What is the concept of a return value? Is it possible to have a return value in an expression?
Ans: A return function is a function which returns a value after the implementation of the function. The return function is used when we pass user defined function.
8. If a function does not have a return statement, what is the return value of a call to that function?
9. How do you make a function variable refer to the global variable?
10. What is the data type of None?
Ans: NoneType
11. What does the sentence import areallyourpetsnamederic do?
12. If you had a bacon() feature in a spam module, what would you call it after importing spam?
13. What can you do to save a programme from crashing if it encounters an error?
Ans: Exception handling
14. What is the purpose of the try clause? What is the purpose of the except clause?
Ans: The try block : test a block of code for errors. The except block handle the error.

"""