# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xW8VKgKd0bNdiT9G56I74fXWA1zpx-h3
"""

#Write a Python program to find sum of elements in list?
list1 = [1,2,3,4,5]
total = 0
for i in list1:
  total = total+i
print(total)

list1 = [1,2,3,4,5]
sum(list1)

def sumlist(list):
  total = 0
  for i in range(len(list)):
    total = total+list[i]
  print(total)

list1 = [1,2,3,4,5]
sumlist(list1)

# Write a Python program to Multiply all numbers in the list?
def mullist(list):
  x = 1
  for i in range(len(list)):
    x = x*list[i]
  print(x)

list1 = [1,2,3,4,5]
mullist(list1)

#Write a Python program to find smallest number in a list?
min(list1)

list = [22,5,67,34,65,68]
list.sort()

list

list[0]

#Write a Python program to find largest number in a list?
list[-1]

#Write a Python program to find second largest number in a list?
list[-2]

#Write a Python program to print even numbers in a list?
def oddeven(l):
  for i in l:
    if i%2==0:
      print(i,"even")
    else:
      print(i, "odd")

oddeven(list)

#Write a Python program to Remove empty List from List?
for i in list1:
  if i!=[]:
   print(i)

#Write a Python program to Count occurrences of an element in a list?
def countX(list, x):
    count = 0
    for i in list:
        if (i == x):
            count = count + 1
    return count