# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/128f4vRrzo_haz0V_i9HgxX1OiqUHrvyf
"""

#Write a Python program to find words which are greater than given length k?
str1= "Write a Python program to find words which are greater than given length k?"
list = str1.split()
def greatx(list,x):
  for i in list:
    if len(i)>x:
      print(i)

greatx(list,4)

#Write a Python program to split and join a string?
str2 = "Write a Python program to split and join a string?"
list1= str2.split()
x = (" ".join(list1))
print(x)

#Write a Python program for removing i-th character from a string?
str3 = "Write a Python program for removing i-th character from a string?"
list3 = str3.split()
list3.pop(4)

x = list3[0:3]+list3[3:]
print(x)

# Write a Python program to find uncommon words from two Strings?
str3 = "Write a Python program to find uncommon words from two Strings?"
str4 = "Write a Python program for removing i-th character from a string?"
list4 = str3.split()
list5 = str4.split()
l1 = []
for i in list4:
  if i not in list5:
    l1.append(i)
for i in list5:
  if i not in list4:
    l1.append(i)

l1

# Write a Python to find all duplicate characters in string?
str6 = "Write a Python to find all duplicate characters in a string?"
l6=str6.split()
l7 =[]
l8 =[]
for i in l6:
  if i not in l7:
    l7.append(i)
  else:
    l8.append(i)

l8

#Write a Python Program to check if a string contains any special character?